name: setup environment
description: Install node + yarn
runs:
  using: 'composite'
  steps:
    - name: Setup node
      uses: actions/setup-node@v3
      with:
        node-version: 18.14.x
        cache: yarn
    - name: Install
      run: yarn
      shell: bash